---
- name : Deploy services
  hosts: all
  vars_files: ./vars/gitvars.yml
  tasks:
    - name: Stop docker-compose
      docker_compose:
          project_src: /home/{{ ansible_user }}/certpub-eth/web
          state: absent
    - name: System prune
      shell:
          cmd: docker system prune -f
